server:
  port: 8989
# 我们配置了三个数据，其中第一个作为默认数据源也就是我们的master数据源。主要是写操作，那么读操作交给我们的slave1跟slave2
spring:
  datasource:
    master:
      url: jdbc:mysql://${linux.port.master.mysql}/wtf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 158262751
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  # 其中 master 数据源一定是要配置 作为我们的默认数据源，其次cluster集群中，其他的数据不配置也不会影响程序员运行，如果你想
  # 添加新的一个数据源 就在cluster下新增一个数据源即可，其中key为必须项，用于数据源的唯一标识，以及接下来切换数据源的标识。
    cluster:
      - key: slave1
        url: jdbc:mysql://${linux.port.slave.slave1}/wtf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        idle-timeout: 20000
        username: root
        password: 158262751
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      - key: slave2
        url: jdbc:mysql://${linux.port.slave.slave2}/wtf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 158262751
        driver-class-name: com.mysql.cj.jdbc.Driver
