server:
  port: 8083
  address: 127.0.0.1
  servlet:
    context-path: /spring-boot

# 日志文件配置,用之前需要排除 logback 的依赖
logging:
  config: classpath:log4j/log4j2.yml
#  level:
#    com.xwz.boot.mapper: debug

mybatis-plus:
  #配置包扫描位置
  configuration:
    #适配驼峰命名法
    map-underscore-to-camel-case: true #默认为true
  #    interceptors: com.xwz.boot.configure.data.MybatisInterceptor 失败
  type-aliases-package: com.java.boot.base.model
  mapper-locations: classpath:com/java/boot/base/mapper/*.xml

  ## 日志文件配置,用之前需要排除 logback 的依赖
  #logging:
  #    config: classpath:log4j/log4j2-spring.xml
  #  config: classpath:log4j/log4j2.yml
  #  level:
  #      com.xwz.boot.mapper: debug
  #  config: classpath:log4j/log4j2.yml
  #  config: classpath:log4j2-spring.xml #可行


  #自定义类型转换
  #  type-handlers-package: com.web.pro.model.handler
#
#  #开启注解班
#
##  cache:
##    type: redis
##    cache-names: redisCahe
#logging:
#  level:
#    com.web.pro.mapper: debug
#    root: debug
#    org.org.mybatis: debug
#    org.springframework: debug