version: '3'
services:
  node1:
    image: elasticsearch:6.4.3
    container_name: node1
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=192.168.150.21:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/node0:/usr/share/elasticsearch/data
      - ./logs/node0:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
  es-head:
    image: tobias74/elasticsearch-head:6
    container_name: es-head
    restart: always
    ports:
      - "9100:9100"