cluster.name: myapp
node.name: node3
network.bind_host: 0.0.0.0
network.publish_host: 192.168.26.22
http.port: 9202
transport.tcp.port: 9302
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
discovery.zen.ping.unicast.hosts: ["192.168.26.22:9300","192.168.26.22:9301","192.168.26.22:9302"]
discovery.zen.minimum_master_nodes: 2